# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: bap-apis
  namespace: bap-apis
  labels:
    app: bap-apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bap-apis
  template:
    metadata:
      labels:
        app: bap-apis
    spec:
      serviceAccount: ${env_prefix}bap-apis-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: bap-apis
          image: "asia-southeast1-docker.pkg.dev/ondc-l1-accl-180920232021/ondc-l1-repo/bap-api:latest"
          env:
            - name: CONFIG
              value: "/config/config.json"
          volumeMounts:
            - name: config-volume
              readOnly: true
              mountPath: /config/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: bap-apis-config
