# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: bap-adapter-config
  namespace: bap-adapter
data:
  config.json: |
    {
      "projectID": "${project_id}",
      "buyerAppURL": "${buyer_app.url}",
      "subscriptionID": [
        "${pubsub.prefix}-callback-on-search",
        "${pubsub.prefix}-callback-on-select",
        "${pubsub.prefix}-callback-on-init",
        "${pubsub.prefix}-callback-on-confirm",
        "${pubsub.prefix}-callback-on-status",
        "${pubsub.prefix}-callback-on-track",
        "${pubsub.prefix}-callback-on-cancel",
        "${pubsub.prefix}-callback-on-update",
        "${pubsub.prefix}-callback-on-rating",
        "${pubsub.prefix}-callback-on-support",
        "${pubsub.prefix}-callback-on-issue",
        "${pubsub.prefix}-callback-on-issue-status"
      ],
      "ONDCEnvironment": "${ondc_environment}"
    }
